FROM openjdk:17.0.2-slim-buster
ENV JAVA_OPTIONS ""
ENV APP_JAR_NAME demo-project
ENV APP_JAR_VERSION 1.0
ENV SPRING_BOOT_JAR_FILE_NAME="$APP_JAR_NAME-$APP_JAR_VERSION.jar"
COPY target/$SPRING_BOOT_JAR_FILE_NAME  $SPRING_BOOT_JAR_FILE_NAME

ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTIONS -jar  /$SPRING_BOOT_JAR_FILE_NAME" ]
EXPOSE 8080