spring:
  application:
    name: demo-project
  main:
    allow-bean-definition-overriding: true
  data:
    jdbc:
      repositories:
        enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:h2:mem:demoprojectdb
    username: root
    password: password
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 100
      minimum-idle: 5
      pool-name: demo-pool
      max-lifetime: 2000000
      connection-timeout: 30000
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      schema-locations: classpath:/schema.sql

server:
  port: 8080

coincap-client:
  request-options:
    access-token: 5859461c-df0a-42b3-a0ba-14410c4fd2b6
    encoding: gzip
    base-url: https://api.coincap.io/v2
  adapters:
    assets:
      retry-attempts: 5
      retry-delay: 2000


app:
  scheduled:
    fix-rate: 60000
