spring:
  application:
    name: demo-project
  main:
    allow-bean-definition-overriding: true
  data:
    jdbc:
      repositories:
        enabled: true
  datasource:
    url: jdbc:h2:mem:demoprojectdb
    username: root
    password: password
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 100
      minimum-idle: 5
      pool-name: demo-pool
      max-lifetime: 2000000
      connection-timeout: 30000
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

adapters:
  assets:
    retryAttempts: 5
    retryDelay: 2000
